export { default as HomeImage } from './home.svg'
export { default as Phone } from './phone.svg'
export { default as React } from './react.svg'
export { default as Sdd } from './Sdd.svg'
export { default as QR } from './QR.png'
export { default as backGoundMobile } from './backGoundMobile.svg'
export { default as SddDark } from './SddDark.svg'
export { default as Dino } from './Dino.svg'
export { default as Traced } from './Traced.png'
export { default as HomeMobile} from './HomeMobile.svg'
export { default as Logo } from './Logo.svg'
export { default as TracedLight } from './tracet.png'
export { default as ContactIllustration } from './ContactIllustration.png'
export { default as ContactIllustrationBlack } from './ContactIllustrationBlack.png'
export { default as Discord  } from './discord.png'
export { default as WhatsApp  } from './whatsapp.png'
export { default as Git  } from './git.png'
export { default as Insta  } from './insta.png'
export { default as Link  } from './link.png'


export { default as sis  } from './slice.svg'
export { default as ilu  } from './ilu.svg'